#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"
linter_exit_code=1

all_ts_files=$(git diff --cached --diff-filter=d --name-only | grep .ts$)
all_tsx_files=$(git diff --cached --diff-filter=d --name-only | grep .tsx$)

echo "${NC}Checking for Typescript errors"
npx tsc --noEmit

echo "${NC}Linting with ESLint and Prettier"
lerna run lint

echo "${NC}Running tests on changed files"
lerna run test -- --bail --findRelatedTests

linter_exit_code=$?

git add -f $all_ts_files $all_tsx_files

if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Errors have occurred during pre-commit checks"
  exit 1
else
  echo "${GREEN} ✔ Typescript and Eslint did not find any errors"
  exit 0
fi
