version: "3.9"
services:
  api:
    build: ./packages/api
    ports:
      - "5000:5000"
    links:
      - database
      - redis
  frontend:
    build: ./packages/frontend
    ports:
      - "5001:5001"
  redis:
    image: "redis:alpine"
  database:
    image: "postgres:13.1"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - jobsearchorg:/var/lib/postgresql/data
volumes:
  jobsearchorg:
    external: true
